spring:
  webflux:
    base-path: /api/v1
  datasource:
    url: jdbc:postgresql://localhost:5432/iprody
    username: iprody
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    generate-ddl: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
    enabled: true
