spring:
  webflux:
    base-path: ${BASE_PATH}
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: liquibase, health, prometheus
  endpoint:
    health:
      show-details: always
springdoc:
  show-actuator: true
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  error:
    include-message: always
---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master-test.yml
server:
  error:
    include-message: always
---
spring:
  config:
    activate:
      on-profile: e2e
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-e2e.yml
    drop-first: true
management:
  endpoints:
    web:
      exposure:
        include: liquibase, health, prometheus, mappings
server:
  error:
    include-message: always