version: "3.9"
services:
  postgres:
    image: postgres:15.3-alpine
    container_name: postgres_e2e
    environment:
      POSTGRES_DB: ${UPS_DB_NAME}
      POSTGRES_USER: ${UPS_DB_USERNAME}
      POSTGRES_PASSWORD: ${UPS_DB_PASSWORD}
    volumes:
      - ./pgdata_e2e:/var/lib/postgresql/data
    networks:
      - postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U iprody" ]
      interval: 6s
      timeout: 5s
      retries: 5
    restart: always

  user-profile-service:
    container_name: user-profile-service
    build:
      context: ../user-profile-service
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: e2e
      BASE_PATH: ${UPS_API_BASE_PATH}
      DB_HOST: ${UPS_DB_HOST}
      DB_PORT: ${UPS_DB_PORT}
      DB_NAME: ${UPS_DB_NAME}
      DB_USERNAME: ${UPS_DB_USERNAME}
      DB_PASSWORD: ${UPS_DB_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy

networks:
  postgres: